Algoritmo "Nome"
// Disciplina   : [Linguagem e Logica de Programacao]
// Professor   : Marcos Monteiro 
// Descrição   : Exemplo de um programa que mostra o nome digitado
// Autor(a)    : Douglas Luiz de Oliveira rodrigues
// Data atual  : 26/10/2022

Var
// Secao de Declaracoes das variaveis 
nome: caractere;

Inicio
// Secao de Comandos, procedimento, funcoes, operadores, etc...  
  escreva("Digite seu nome: ")
    leia(nome)
  escreva("Seja bem-vindo: "+ nome)

Fimalgoritmo