Algoritmo "Constantes"
// Disciplina   : [Linguagem e Logica de Programacao]
// Professor   : Marcos Monteiro 
// Descrição   : Mostra o valor de PI
// Autor(a)    : Douglas Luiz de Oliveira Rodrigues
// Data atual  : 26/10/2022

Var
// Secao de Declaracoes das variaveis 

Inicio
// Secao de Comandos, procedimento, funcoes, operadores, etc... 
    escreva("O valor de primitivo de PI e: ", PI)

Fimalgoritmo