Algoritmo "ImprimeFor1a10"
// Disciplina   : [Linguagem e Logica de Programacao]
// Professor   : Marcos Monteiro 
// Descrição   : Impressao de numeros de 1 a 10
// Autor(a)    : Douglas Luiz de Oliveira Rodrigues
// Data atual  : 26/10/2022

Var
// Secao de Declaracoes das variaveis  
j: inteiro;

Inicio
// Secao de Comandos, procedimento, funcoes, operadores, etc...  
    escreval("Imprimindo de 1 a 10: ")
    para j de 1 ate 10 faca
        escreva(j)
    fimpara
    
Fimalgoritmo