Algoritmo "ImprimeFor10a1"
// Disciplina   : [Linguagem e Logica de Programacao]
// Professor   : Marcos Monteiro 
// Descrição   : Impressao de numeros de 10 a 1
// Autor(a)    : Douglas Luiz de Oliveira Rodrigues
// Data atual  : 26/10/2022

Var
// Secao de Declaracoes das variaveis 
j: inteiro;

Inicio
// Secao de Comandos, procedimento, funcoes, operadores, etc... 
    escreval("Imprimindo de 10 a 1: ")
    para j de 10 ate 1 passo j-1 faca
        escreva(j)
    fimpara
    
Fimalgoritmo